import type { Metadata } from "next";
import { Hanken_Grotesk } from "next/font/google";
import "./globals.css";

const hankenGrotesk = Hanken_Grotesk({
  subsets: ["latin"],
  variable: "--font-hanken",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${hankenGrotesk.variable} ${hankenGrotesk.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <header className="flex items-center justify-between px-8 py-5 border-b border-white/10 w-full bg-[#161616]">
        <div className="flex items-center gap-8">
          <h1 className="text-2xl font-bold text-white">Mapa de Corrosion</h1>
        </div>
        <div className="flex items-center gap-4">
          <div className="w-6 h-6 bg-white/10 rounded-full"></div> {/* Icono */}
        </div>
      </header>
        {children}
        </body>
    </html>
  );
}
